# DIMENSIONS
TILE_SIZE = 64  # TILES ARE SQUARE HEIGHT == WIDTH
SCREEN_WIDTH = 12*TILE_SIZE
SCREEN_HEIGHT = 8*TILE_SIZE
SAND_HEIGHT = 20
WATER_BOTTOM = SCREEN_HEIGHT - 2*TILE_SIZE

# COLORS
WATER_COLOR = (52, 222, 235)
SAND_COLOR = (246, 230, 178)

#GAME DYNAMICS
NUM_MINNOWS = 5